### PR TITLE
Added variable centering

### PR DESCRIPTION
**Pull request by Oxymoron290**

### CODE REVIEW

**Review by ajscalise — COMMENTED** [review]
Would you explain what action I would need to take if this is true or false?

**Comment by Oxymoron290** [comment]
if true - center the variable, otherwise, don't.

**Comment by ajscalise** [comment]
I don't understand what it means to center the variable.

**Comment by theWakandan** [comment]
Should the flexspec doc have boolean data type added to that tag?

**Comment by Oxymoron290** [comment]
flexspec doc?

**Comment by Oxymoron290** [comment]
I see what you meant (I think) and I made another commit.

**Review by theWakandan — APPROVED** [review]

**Pull request merged**
